# Generated by Django 4.2.7 on 2023-11-17 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='creared_at',
            new_name='created_at',
        ),
    ]
