# Generated by Django 4.2.7 on 2023-11-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_creared_at_chat_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='response',
            field=models.TextField(),
        ),
    ]
